// O conteúdo define ferramentas e objetivos de uma simulação contínua.
// Não há perguntas, gabaritos ou votação.
export const CARDS = [
  {
    id: "builder",
    name: "Construtor",
    model: "Barbarian",
    icon: "tools",
    color: "#edba80",
    cost: 3,
    description:
      "Sozinho leva 36 s. Cada canteiro isolado soma uma frente de trabalho.",
    lesson:
      "Delegação: cada agente recebe uma frente concreta. Dois Construtores isolados constroem em metade do tempo; sem canteiro livre eles disputam o mesmo checkout.",
  },
  {
    id: "worktree",
    name: "Worktree",
    model: "Rogue_Hooded",
    icon: "branch",
    color: "#83dbb1",
    cost: 2,
    description:
      "Abre um canteiro isolado nesta frente. Até 2 por frente, e duram a partida.",
    lesson:
      "Uma worktree é um diretório de trabalho, e cabe um agente em cada. Abrir um canteiro libera mais um Construtor em paralelo; sem canteiro livre eles voltam ao mesmo checkout. Worktree não substitui sandbox.",
  },
  {
    id: "reviewer",
    name: "Revisor",
    model: "Mage",
    icon: "mage",
    color: "#c9a2fa",
    cost: 2,
    description:
      "Valida e integra a obra. 9 s, +3 s por falha e +5 s por frente extra.",
    lesson:
      "Revisão acontece sobre uma entrega concreta. Falhas custam tempo, e cada frente paralela precisa ser convergida: paralelismo compra latência pagando coordenação.",
  },
  {
    id: "harness",
    name: "Harness",
    model: "Knight",
    icon: "shield",
    color: "#79bfff",
    cost: 2,
    description: "Bloqueia entrega sem revisão e comandos do caos neste alvo.",
    lesson:
      "O harness aplica permissões e bloqueia ações fora das regras. Dar uma instrução não é o mesmo que restringir a ferramenta.",
  },
];
export const SITES = [
  {
    id: 0,
    name: "Portal",
    icon: "crown",
    purpose: "Reconecte as rotas do reino.",
    x: -5.6,
    z: -8.4,
  },
  {
    id: 1,
    name: "Forja",
    icon: "tools",
    purpose: "Restaure a fonte de energia.",
    x: 0,
    z: 10.4,
  },
  {
    id: 2,
    name: "Muralha",
    icon: "shield",
    purpose: "Erga a defesa da Cidadela.",
    x: 5.6,
    z: -8.4,
  },
];
export const STORY = {
  title: "Reconstrua antes da tempestade",
  description:
    "O caos rompeu o Portal, apagou a Forja e derrubou a Muralha. Mobilize sua guilda: construa, revise e entregue três níveis em cada frente.",
  maxLevel: 3,
  // Um Construtor sozinho leva a obra inteira. Cada canteiro isolado acrescenta
  // uma frente de trabalho, e a revisão cobra a convergência depois.
  buildSeconds: 36,
  reviewSeconds: 9,
  integrationSeconds: 5,
  conflictRate: 0.5,
  maxWorktrees: 2,
  maxEnergy: 12,
  regen: 0.65,
  scoreSafe: 100,
  scoreUnsafe: 40,
};
// Parâmetros do estudo em campo. O acerto corta metade do tempo que falta na
// tarefa e soma pontos: entregar rápido deixa de ser suficiente para vencer.
export const STUDY = {
  bonus: 20,
  speedup: 0.5,
  revealSeconds: 4.5,
};
// Perguntas tiradas da apresentação. O índice correto e a explicação vivem só
// aqui: missions.mjs não é servido ao navegador e o snapshot só revela os dois
// depois que a pessoa responde.
export const QUESTIONS = [
  {
    id: "harness",
    topic: "Harness",
    prompt: "O que o harness faz, além de chamar o modelo?",
    options: [
      "Treina o modelo com os arquivos do repositório",
      "Monta contexto, roda ferramentas, aplica sandbox e estado",
      "Troca de fornecedor quando o modelo erra",
    ],
    answer: 1,
    why: "O harness é a camada que faz o modelo trabalhar: contexto, modelo, ferramentas, sandbox e aprovação, estado entre turnos.",
  },
  {
    id: "workflow",
    topic: "Workflows",
    prompt: "O que separa um workflow de um agente?",
    options: [
      "No workflow o caminho está definido em código",
      "O workflow roda local; o agente roda na nuvem",
      "O workflow usa um modelo menor",
    ],
    answer: 0,
    why: "Prompt chaining, routing e orchestrator-workers são composições explícitas. No agente, a sequência das ações é decisão do modelo.",
  },
  {
    id: "multiagente",
    topic: "Multiagente",
    prompt: "O ganho de 90,2% do sistema multiagente veio com que custo?",
    options: [
      "Cerca de 15× mais tempo de execução",
      "Quinze subagentes fixos por consulta",
      "Cerca de 15× mais tokens",
    ],
    answer: 2,
    why: "A Anthropic reporta ~15× mais tokens, e que o uso de tokens explica 80% da variação de desempenho no BrowseComp.",
  },
  {
    id: "worktree-shares",
    topic: "Worktree",
    prompt: "O que uma worktree compartilha com o checkout principal?",
    options: [
      "Histórico, objetos e remote; a branch é própria",
      "Nada: é um clone completo e independente",
      "A branch: os dois diretórios usam a mesma",
    ],
    answer: 0,
    why: "Worktree isola diretório e branch sem duplicar o repositório: histórico, objetos e remote continuam compartilhados.",
  },
  {
    id: "worktree-gap",
    topic: "Worktree",
    prompt: "Abriu a worktree e o primeiro teste falhou. Causa provável?",
    options: [
      "A branch nova não tem o histórico do projeto",
      "O remote não foi configurado no novo diretório",
      "Faltou o que o Git ignora: .env e dependências",
    ],
    answer: 2,
    why: "A worktree só leva o que o Git conhece. A correção é declarar o que precisa acompanhar ou usar um hook de bootstrap.",
  },
  {
    id: "worktree-limit",
    topic: "Worktree",
    prompt: "O que a worktree NÃO resolve?",
    options: [
      "Conflito de arquivos entre duas frentes",
      "Coordenação e permissão: worktree não é sandbox",
      "Trabalhar em duas branches ao mesmo tempo",
    ],
    answer: 1,
    why: "Worktree resolve isolamento de arquivo. Coordenação fica com subagentes ou com o orquestrador humano; permissão fica com o harness.",
  },
  {
    id: "subagent-description",
    topic: "Subagentes",
    prompt: "Para que serve o campo description de um subagente?",
    options: [
      "Dizer em que situação a delegação faz sentido",
      "Virar o system prompt do subagente",
      "Definir quais ferramentas ele pode usar",
    ],
    answer: 0,
    why: "name e description são obrigatórios. O corpo do markdown é que vira o system prompt; tools define o conjunto permitido.",
  },
  {
    id: "tool-scope",
    topic: "Permissões",
    prompt: "Por que tirar Write e Edit de um subagente revisor?",
    options: [
      "Porque Write e Edit custam mais tokens",
      "Porque ele herda as permissões do agente principal",
      "Menos ferramentas, menos ações erradas possíveis",
    ],
    answer: 2,
    why: "disallowedTools bloqueia capacidades antes da execução. O escopo de ferramentas faz parte do desenho do agente.",
  },
  {
    id: "second-harness",
    topic: "Orquestração",
    prompt: "Quando um segundo harness se justifica?",
    options: [
      "Sempre que a tarefa tiver mais de duas etapas",
      "Fornecedores diferentes ou frentes longas e independentes",
      "Quando a janela de contexto do primeiro enche",
    ],
    answer: 1,
    why: "Outro harness duplica contexto e coordenação. Comece com a composição mais simples que atende a tarefa.",
  },
  {
    id: "agents-md",
    topic: "Contratos",
    prompt: "Qual é a vantagem do AGENTS.md na raiz do repositório?",
    options: [
      "Markdown versionado que vários harnesses leem",
      "Carrega sozinho em toda chamada, sem custo de tokens",
      "Dispensa a escrita de ADRs",
    ],
    answer: 0,
    why: "Guarda comandos exatos, caminhos proibidos e convenções. Um arquivo gigante perde hierarquia: regra demais nivela tudo.",
  },
  {
    id: "adr-shape",
    topic: "ADR",
    prompt: "Quais seções formam um ADR no formato Nygard?",
    options: [
      "Resumo, requisitos, cronograma e responsáveis",
      "Problema, hipótese, experimento e métrica",
      "Título, status, contexto, decisão e consequências",
    ],
    answer: 2,
    why: "Costuma caber em uma ou duas páginas e fica versionado junto do código.",
  },
  {
    id: "adr-agents",
    topic: "ADR",
    prompt: "Por que o ADR ajuda no trabalho com agentes?",
    options: [
      "Guarda a decisão entre sessões, mesmo após compactação",
      "Impede o agente de alterar arquivos de infraestrutura",
      "Reduz os tokens que cada sessão consome",
    ],
    answer: 0,
    why: "Os agentes não precisam conversar diretamente: o estado compartilhado fica no repositório.",
  },
  {
    id: "incident",
    topic: "Case",
    prompt: "O que derrubou o site do BuscaGames por cerca de 20 minutos?",
    options: [
      "Um agente apagou a base de dados de produção",
      "A Steam bloqueou o scraping e a API parou",
      "Worker de I/O carregou modelo pesado e saturou a VPS",
    ],
    answer: 2,
    why: "4 vCPU compartilhados pelo site e pelos workers, 15 GB de RAM no pico. Sem limites de recurso, a falha atingiu o host inteiro.",
  },
  {
    id: "tacit",
    topic: "Case",
    prompt: "O agente inspecionou os containers. O que ainda faltava?",
    options: [
      "A regra de subir cada serviço isolado, não versionada",
      "Permissão para reiniciar o container após o deploy",
      "Janela de contexto maior para ler o repositório",
    ],
    answer: 0,
    why: "Inspecionar um ambiente mostra o que existe. Não revela uma convenção que nunca foi escrita.",
  },
  {
    id: "autonomy",
    topic: "Autonomia",
    prompt: "Por reversibilidade e blast radius, o que exige aprovação?",
    options: [
      "Qualquer mudança de código acima de 100 linhas",
      "Produção: dados, permissões e recursos compartilhados",
      "Toda execução de teste que use rede",
    ],
    answer: 1,
    why: "Local e efêmero admite autonomia alta; staging compartilhado pede regras e revisão seletiva; produção fica atrás de aprovação humana.",
  },
  {
    id: "checklist",
    topic: "Autonomia",
    prompt: "Qual pergunta NÃO está no checklist antes da autonomia?",
    options: [
      "Existe rollback se o próprio host falhar?",
      "CPU, memória e cotas estão declaradas?",
      "Qual modelo tem o melhor benchmark na linguagem?",
    ],
    answer: 2,
    why: "O checklist é: qual ambiente, qual o limite, como reverter e se a ação precisa de aprovação humana.",
  },
  {
    id: "cost",
    topic: "Custo",
    prompt: "Que custo o paralelismo acrescenta além da fatura do modelo?",
    options: [
      "Tempo de convergir e risco em ambiente compartilhado",
      "Licenças adicionais por subagente aberto",
      "Armazenamento: cada worktree duplica o histórico",
    ],
    answer: 0,
    why: "Cada agente replica parte do contexto; cache reduz preço, mas não zera uso. Ação sobre ambiente compartilhado soma risco que não está na fatura.",
  },
  {
    id: "contexto",
    topic: "Contexto",
    prompt: "Por que uma sessão longa vira gargalo?",
    options: [
      "O modelo esquece a linguagem do projeto",
      "A compactação pode apagar a decisão por trás do código",
      "A janela de contexto reduz a velocidade de resposta",
    ],
    answer: 1,
    why: "Leitura de arquivo, testes e stack traces enchem a janela. A compactação reduz volume, mas pode levar junto o contexto que justificou decisões anteriores.",
  },
  {
    id: "codex-plataforma",
    topic: "Panorama",
    prompt: "Qual ferramenta publicou o harness como plataforma aberta?",
    options: ["Cursor", "Kiro", "Codex"],
    answer: 2,
    why: "Em agosto de 2026 a OpenAI apresentou o Codex como plataforma e tratou o harness como uma camada reutilizável do sistema.",
  },
  {
    id: "kiro",
    topic: "Panorama",
    prompt: "O que caracteriza o Kiro no panorama de 2026?",
    options: [
      "Abordagem spec-first, com steering files em .kiro/steering",
      "É MIT, model-agnostic e self-hosted",
      "O agente vive dentro do editor",
    ],
    answer: 0,
    why: "OpenCode é o MIT, model-agnostic e self-hosted; o Cursor é o que põe o agente dentro da IDE. O Kiro, da AWS, parte de especificações.",
  },
  {
    id: "orchestrator",
    topic: "Workflows",
    prompt: "Qual composição põe um agente para dividir e consolidar?",
    options: ["Prompt chaining", "Orchestrator-workers", "Routing"],
    answer: 1,
    why: "Prompt chaining são etapas em sequência e routing classifica e encaminha. Em orchestrator-workers um agente divide o trabalho e consolida o resultado.",
  },
  {
    id: "evaluator",
    topic: "Workflows",
    prompt: "O que o evaluator-optimizer acrescenta às outras composições?",
    options: [
      "Classificação e encaminhamento por tipo",
      "Frentes independentes rodando em paralelo",
      "Um loop de produção e crítica",
    ],
    answer: 2,
    why: "Routing classifica e encaminha; parallelization roda frentes independentes. O evaluator-optimizer adiciona crítica em loop sobre o que foi produzido.",
  },
  {
    id: "browsecomp",
    topic: "Multiagente",
    prompt: "O que explica 80% da variação de desempenho no BrowseComp?",
    options: [
      "O uso de tokens",
      "O número de subagentes abertos",
      "O tamanho do repositório analisado",
    ],
    answer: 0,
    why: "É o dado que ajuda a entender por que o sistema multiagente rende mais e custa cerca de 15 vezes mais tokens.",
  },
  {
    id: "lider",
    topic: "Multiagente",
    prompt: "Como o agente líder trabalha no sistema multiagente?",
    options: [
      "Divide a própria janela de contexto entre os subagentes",
      "Planeja e abre subagentes com janelas próprias",
      "Executa as etapas em sequência e resume no fim",
    ],
    answer: 1,
    why: "O líder registra o plano e abre subagentes em paralelo. Cada um tem a própria janela e devolve achados condensados.",
  },
  {
    id: "simples-primeiro",
    topic: "Orquestração",
    prompt: "Antes de somar ferramentas, o que já resolve a maior parte?",
    options: [
      "Um harness bem configurado, com subagentes e paralelismo",
      "Dois harnesses de fornecedores diferentes",
      "Um modelo maior para todas as tarefas",
    ],
    answer: 0,
    why: "Subagentes já separam contexto e responsabilidade dentro da mesma ferramenta, e sessões em segundo plano cobrem boa parte do paralelismo cotidiano.",
  },
  {
    id: "worktree-add",
    topic: "Worktree",
    prompt: "Qual comando abre outra worktree numa branch nova?",
    options: [
      "git clone --branch feature/api ../api",
      "git worktree list --new feature/api",
      "git worktree add ../api -b feature/api",
    ],
    answer: 2,
    why: "git worktree list mostra o mapa dos checkouts e git worktree remove desfaz, sem criar outro histórico nem outro remote.",
  },
  {
    id: "isolation-frontmatter",
    topic: "Subagentes",
    prompt: "O que isolation: worktree faz no frontmatter de um subagente?",
    options: [
      "Pede que o subagente rode num diretório isolado",
      "Impede o subagente de usar ferramentas de escrita",
      "Faz o subagente herdar o modelo do agente principal",
    ],
    answer: 0,
    why: "Escrita se bloqueia com disallowedTools, e a herança do modelo é model: inherit. O frontmatter reúne as três coisas.",
  },
  {
    id: "agents-md-governanca",
    topic: "Contratos",
    prompt: "Qual é a governança do AGENTS.md hoje?",
    options: [
      "É um padrão interno da Anthropic",
      "É mantido junto com a especificação do Git",
      "Foi doado à Agentic AI Foundation",
    ],
    answer: 2,
    why: "Criado em agosto de 2025 e doado em dezembro de 2025, o que permite que harnesses diferentes leiam o mesmo arquivo.",
  },
  {
    id: "agents-md-tamanho",
    topic: "Contratos",
    prompt: "Qual é o risco de um AGENTS.md gigante?",
    options: [
      "Regra demais faz tudo parecer igualmente importante",
      "Ele deixa de ser lido por outros harnesses",
      "Ele passa a exigir aprovação humana a cada leitura",
    ],
    answer: 0,
    why: "Um arquivo grande perde hierarquia. É melhor manter documentos menores e específicos.",
  },
  {
    id: "adr-radar",
    topic: "ADR",
    prompt: "Qual é a origem do formato de ADR usado na apresentação?",
    options: [
      "Um padrão publicado pela Agentic AI Foundation",
      "O formato Nygard, popularizado em 2011",
      "Um anexo da documentação do Git",
    ],
    answer: 1,
    why: "A ThoughtWorks marcou ADR como Adopt no Technology Radar. O formato tem título, status, contexto, decisão e consequências.",
  },
  {
    id: "dois-harnesses-case",
    topic: "Case",
    prompt: "Por que dois harnesses fizeram sentido no BuscaGames?",
    options: [
      "As frentes de coleta, API e interface eram independentes",
      "Porque um harness sozinho não suporta worktrees",
      "Para reduzir o custo de tokens pela metade",
    ],
    answer: 0,
    why: "As frentes avançavam ao mesmo tempo e eram longas, que é uma das condições para considerar um segundo harness.",
  },
  {
    id: "fluxo",
    topic: "Case",
    prompt: "Onde começa uma mudança estrutural no fluxo do case?",
    options: [
      "Pela implementação, com o ADR depois do merge",
      "Pela aprovação do deploy em produção",
      "Pelo contrato versionado, com ADR antes do código",
    ],
    answer: 2,
    why: "A tarefa abre na worktree, lê o contrato, gera ADR se for estrutural, implementa e passa por revisão humana no merge.",
  },
  {
    id: "estado-compartilhado",
    topic: "Isolamento",
    prompt: "Como as duas frentes trocavam estado no BuscaGames?",
    options: [
      "Por um canal direto entre os agentes",
      "Pelos documentos versionados no repositório",
      "Por um banco de memória compartilhado",
    ],
    answer: 1,
    why: "Os agentes não conversavam diretamente. AGENTS.md e ADRs eram o canal entre as sessões.",
  },
  {
    id: "decisao-incidente",
    topic: "Case",
    prompt: "Que decisão operacional causou o incidente do case?",
    options: [
      "Trocar o Postgres por um banco gerenciado",
      "Rodar o scraping da Steam em horário de pico",
      "Reaproveitar o worker de ingestão que já existia",
    ],
    answer: 2,
    why: "A tradução local com NLLB-200 sobre CTranslate2 entrou no worker existente e foi para o ambiente compartilhado. O código funcionava; faltou a barreira.",
  },
  {
    id: "tipos-de-risco",
    topic: "Autonomia",
    prompt: "Editar código e operar um ambiente pedem o quê do harness?",
    options: [
      "O mesmo tratamento, já que os dois alteram arquivos",
      "Políticas diferentes de execução e aprovação",
      "Aprovação humana nos dois casos, sempre",
    ],
    answer: 1,
    why: "Deploy, migration, consumo de recursos compartilhados e mudança de permissões têm blast radius próprio e pedem política própria.",
  },
  {
    id: "contratos-operacionais",
    topic: "Autonomia",
    prompt: "O que virou regra versionada depois do incidente?",
    options: [
      "Serviço de produção declara limites de CPU e memória",
      "Todo deploy passa a ser feito só por humanos",
      "Nenhum agente pode acessar o servidor",
    ],
    answer: 0,
    why: "Junto com ela: deploy compartilhado exige aprovação humana, decisão estrutural gera ADR e o escopo de ferramentas segue a função do subagente.",
  },
  {
    id: "primeiro-passo",
    topic: "Aplicação",
    prompt: "Por onde começar num repositório novo?",
    options: [
      "Pelo segundo harness, para comparar abordagens",
      "Pela automação do deploy em produção",
      "Pelo AGENTS.md, com comandos e caminhos proibidos",
    ],
    answer: 2,
    why: "Depois vêm o primeiro ADR, a restrição de ferramentas dos subagentes e a retenção de ações irreversíveis atrás de aprovação.",
  },
  {
    id: "codex-token",
    topic: "Custo",
    prompt: "O que mudou na cobrança do Codex em abril de 2026?",
    options: [
      "Passou a cobrar por sessão aberta",
      "Passou a cobrar por token; a entrada em cache custa menos",
      "Passou a ser gratuito para repositórios públicos",
    ],
    answer: 1,
    why: "Cache reduz preço, mas não zera uso: cada agente ainda replica parte do contexto.",
  },
  {
    id: "isolation",
    topic: "Isolamento",
    prompt: "O que caracteriza orchestrator-worker frente a um swarm?",
    options: [
      "Mais estado compartilhado e coordenação emergente",
      "Um único agente executando etapas em sequência",
      "Estado separado e depuração mais simples de reconstruir",
    ],
    answer: 2,
    why: "No BuscaGames os subagentes trabalhavam sem conversar entre si, e documentos versionados foram o canal entre as frentes.",
  },
];
